@baseUrl = http://localhost:4000/api
POST {{baseUrl}}/produtos
Content-Type: application/json

{
  "productName": "Estampa 'Lobo Geométrico'",
  "description": "Design vetorial de alta qualidade.",
  "price": 89.90,
  "imageUrl": "https://via.placeholder.com/300"
}